<?php

namespace App\Filament\Resources;

use App\Filament\Resources\MailerSettingResource\Pages;
use App\Filament\Resources\MailerSettingResource\RelationManagers;
use App\Models\Job;
use App\Models\MailerSetting;
use App\Models\Option;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class MailerSettingResource extends Resource
{
    protected static ?string $model = Option::class;
    protected static ?string $slug = "mail-settings";
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static ?string $navigationLabel = "إعدادات البريد المرسل";

    protected static ?string $label = "إعدادات البريد المرسل";
    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }


    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('إعدادات البريد المرسل')->schema([
                    Forms\Components\Select::make('work_id')->options(Job::whereNotNull('excel_id')->latest()->pluck('name', 'id'))->label('الوظيفة')->required(),
                    Forms\Components\Textarea::make('accepted_template')->required()->label('قالب بريد القبول'),
                    Forms\Components\Toggle::make('send_accepted')->required()->label('إرسال بريد للمقبولين'),

                    Forms\Components\Textarea::make('reject_template')->required()->label('قالب بريد غير المقبولين'),
                    Forms\Components\Toggle::make('send_rejected')->required()->label('إرسال بريد غير المقبولين'),
                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('work.name')->label('الوظيفة'),

            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMailerSettings::route('/'),
            'create' => Pages\CreateMailerSetting::route('/create'),
            'edit' => Pages\EditMailerSetting::route('/{record}/edit'),
        ];
    }
}
