<?php

namespace App\Models;

use App\Observers\JobObServe;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    use HasFactory;

    protected $guarded = [];
protected $withCount=[
    'groups'
];
protected $casts=[
    'end_date' => 'date'
];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    self::observe(JobObServe::class);
    }

    public function groups()
{
    return $this->hasMany(Group::class);
}

    public function asks()
    {
        return $this->hasMany(Ask::class);
    }
}
